--- #YAML:1.0
name:               File-MultipleDiff
version:            0.06
abstract:           Compare multiple files
author:
    - Mart E. Rivilis <rivilism@cpan.org>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Algorithm::Diff:  1.19
    perl:             5.006
    Tie::File:        0.97
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
